Commerce7/admin-ui

Dockerfile
build/production/buildspec.yml

Update deployment for Storybook

Update deployment for Storybook

---

Dockerfile
build/production/buildspec.yml
package.json

Add npm publish to deployment
This requires that the PR has the package.json version updated or the NPM publish will fail.

Add npm publish to deployment

---

package.json
src/input/Input.js
src/stories/Releases.stories.mdx

@JakeHildy this is so we can do `inputmode=tel`, etc (this is mainly so touch devices show the correct keyboard)
Blocked by #12

Added inputMode prop to Input component

---

package.json
src/index.js
src/selectButton/SelectButton.js
src/selectButton/SelectButton.stories.js
src/selectButton/SelectButton.styles.js
src/selectButton/index.js
src/selectButton/theme.js
src/stories/Releases.stories.mdx

@tlouth19 I think this is most of the way there. I wasn't 100% sure what to do for focus styling so maybe we can take a look tomorrow.

Admin UI - Add SelectButton component

---

package-lock.json
package.json
src/stories/Releases.stories.mdx
src/tag/Tag.styles.js

@tlouth19 this fixes the Tag X alignment. It only moved up a few px but I think this looks better.

Sc 1510 tag x alignment

---

package.json
src/stories/Releases.stories.mdx
src/ui/theme.js

@JakeHildy we can pull a bunch of config out of admin once this is in here!

Added box shadow and media queries to global theme

---

package-lock.json
package.json
src/breadcrumbs/Breadcrumbs.stories.js
src/stories/Releases.stories.mdx

@tlouth19 this adds the tabs for Breadcrumb docs

Added Tabbed documentation for BreadCrumb

---

package.json
src/card/theme.js
src/stories/Releases.stories.mdx

@tlouth19 this updates the card background colour for dark mode. I checked the c7__ui styles to see if anything else could be standardized to that but the border and background colours are slightly different.

Updated Card background color

---

package.json
src/button/Button.styles.js
src/button/theme.js
src/stories/Releases.stories.mdx

@JakeHildy this adds a `iconColor` to the button theme file so the icons can pull from there instead of `fontColor`

Updated Button icon color config

---

package-lock.json
package.json
src/stories/Releases.stories.mdx

Updated packages

---

package-lock.json
package.json
src/index.js
src/stepper/Step.js
src/stepper/Stepper.js
src/stepper/Stepper.stories.js
src/stepper/Stepper.styles.js
src/stepper/index.js
src/stepper/theme.js
src/stories/Releases.stories.mdx

@tlouth19 this adds the stepper component. I linked it up and tested it with Admin locally so I think it should be good.

Add Stepper component

---

package-lock.json
package.json
src/stepper/Stepper.styles.js
src/stories/Releases.stories.mdx

@tlouth19 updates stepper styling

Updated stepper responsive styling

---

package-lock.json
package.json
src/stories/Releases.stories.mdx
src/ui/theme.js

@JakeHildy I also brought in the styled-normalize from admin (It makes sense to have it here)

Added global styles

---

.storybook/preview-head.html
package.json
src/alert/theme.js
src/common/form/theme.js
src/icon/theme.js
src/message/theme.js
src/stories/Introduction.stories.mdx
src/stories/Releases.stories.mdx
src/table/Th.styles.js
src/table/theme.js
src/tag/Tag.styles.js
src/tag/theme.js
src/text/Text.styles.js
src/text/theme.js
src/ui/theme.js

@JakeHildy I combined a couple stories into one here to avoid a bunch of NPM releases. 
- Updated colors from yesterday based on Andreas feedback
- Upped font size in a couple components
- Upped font weight to 400 global

Updated colors

---

package.json
src/stories/Releases.stories.mdx
src/ui/theme.js

@JakeHildy this is to make the table more readable

Updated slate 200 colour

---

package.json
src/buttonMenu/ButtonMenu.stories.js
src/stories/Releases.stories.mdx

@tlouth19 just a little typo I found and thought I might as well fix it while I was there.

Fixed typo in ButtonMenu docs

---

package-lock.json
package.json
src/alert/Alert.stories.js
src/alert/theme.js
src/stories/Releases.stories.mdx

Added success Alert variant

---

package.json
src/modal/Modal.styles.js
src/modal/ModalBody.styles.js
src/modal/ModalFooter.styles.js
src/stories/Releases.stories.mdx

@JakeHildy this updates some minor css in the modal for smaller viewports. This change was made in the new POS with a custom styles of the modal, so this just brings it over to admin-ui. After this is in admin ill pull off the css from there.

Updated modal css

---

package-lock.json
package.json
src/index.js
src/stories/Releases.stories.mdx
src/subMenu/SubMenu.js
src/subMenu/SubMenu.stories.js
src/subMenu/SubMenu.styles.js
src/subMenu/SubMenuItem.js
src/subMenu/index.js

Blocked by: https://github.com/Commerce7/admin-ui/pull/74

Added SubMenu component to Admin-ui

---

package-lock.json
package.json
src/infoCard/InfoCard.styles.js
src/stories/Releases.stories.mdx

@tlouth19 this centres the label and subtitle

Update Infocard styles

---

package.json
src/buttonMenu/ButtonMenu.js
src/contextMenu/ContextMenuMoreActions.js
src/stories/Releases.stories.mdx

@JakeHildy I missed these two when we updated to React 18

Updated ids to use useId()

---

package.json
src/icon/Icon.stories.js
src/stories/Releases.stories.mdx

Fixed icon docs

---

package-lock.json
package.json
src/index.js
src/noRecords/NoRecords.js
src/noRecords/NoRecords.stories.js
src/noRecords/NoRecords.styles.js
src/noRecords/index.js
src/stories/Releases.stories.mdx

Added NoRecords component

---

package-lock.json
package.json
src/columns/Column.js
src/columns/Columns.js
src/columns/Columns.stories.js
src/columns/Columns.styles.js
src/columns/index.js
src/index.js
src/stories/Releases.stories.mdx

@tlouth19 this adds the columns component

Added Columns component

---

package.json
src/modal/Modal.js
src/modal/ModalContent.js
src/stories/Releases.stories.mdx

@JakeHildy this is the update to the modal we were looking at earlier. I don't think we need a story for this prop

Added scroll prop to modal

---

package-lock.json
package.json
src/stories/Releases.stories.mdx
src/utils/hooks/useWindowSize.js
webpack.config.js

@JakeHildy this cleans up the SSR issues. There were a couple problems. 
- Fixed peerDependencies/dependencies in package.json
- Fixed `useWindowSize()` hook so it doesn't error on the server 
- Replaced `rimaf` with `clean-webpack-plugin`

Fixed SSR issues

---

package-lock.json
package.json
src/index.js
src/picture/Picture.js
src/picture/Picture.stories.js
src/picture/Picture.styles.js
src/picture/index.js
src/stories/Releases.stories.mdx

@tlouth19 this adds the Picture component. I messed around with it quite a bit, let me know what you think. I don't think we need a width prop, it should just expand to width of its container.

Added Picture component

---

package-lock.json
package.json
src/icon/icons/HeartFilled.js
src/icon/icons/index.js
src/stories/Releases.stories.mdx

@andrewkamphuis this adds the heartFilled icon

Add Heart Filled Icon

---

package.json
src/alert/Alert.styles.js
src/stories/Releases.stories.mdx

- updates to add line height property
- updates to add margin-top to icon
- updates version
- updates stories with version changes

Sc 3834 update alert children text

---

package.json
src/stories/Releases.stories.mdx

bumping admin-ui package version so it will deploy

bumping admin-ui package version

---

.npmrc
Dockerfile
package.json
src/stories/Releases.stories.mdx

Add access-public for new NPM version to publish, and update npmrc

Add access-public for new NPM version to publish, and update npmrc

---

src/alert/theme.js
src/ui/theme.js

adds new orange color and applies to warning Alert

---

package-lock.json
package.json
src/checkbox/Checkbox.js
src/checkbox/Checkbox.stories.js
src/checkboxGroup/CheckboxGroup.js
src/checkboxGroup/CheckboxGroup.stories.js
src/common/form/styles.js
src/radio/Radio.js
src/radio/Radio.stories.js
src/radioGroup/RadioGroup.js
src/radioGroup/RadioGroup.stories.js
src/selectButton/SelectButton.js
src/selectButton/SelectButton.stories.js
src/selectButton/SelectButton.styles.js
src/stories/Releases.stories.mdx

@NoahThomlison this updates the SelectButton component to have a "small" variant and adds the button variant to the Radio & Checkbox components.

New form field radio buttons

---

package.json
src/icon/Icon.js
src/icon/Icon.stories.js
src/icon/theme.js
src/stories/Releases.stories.mdx
src/ui/theme.js

updates package
updates release notes
adds text component
exports fontColors from theme.js to be used in style sheet for new icon variant updates stories for icon to include new variant

adds 'text' variant to Icon Component

---

Dockerfile

Set docker to use AWS Linux V2

Set docker to use AWS Linux V2

---

package-lock.json
package.json
src/checkbox/Checkbox.js
src/checkboxGroup/CheckboxGroup.stories.js
src/radio/Radio.js
src/radioGroup/RadioGroup.stories.js
src/selectButton/SelectButton.js
src/stories/Releases.stories.mdx

@NoahThomlison this adds the size prop to the radio and checkboxes so we can use the large size select button easily with Formik.

Update radio and checkbox for large size select button

---

package-lock.json
package.json
src/checkbox/Checkbox.js
src/checkbox/Checkbox.stories.js
src/checkboxGroup/CheckboxGroup.js
src/checkboxGroup/CheckboxGroup.stories.js
src/common/form/styles.js
src/radio/Radio.js
src/radio/Radio.stories.js
src/radioGroup/RadioGroup.js
src/radioGroup/RadioGroup.stories.js
src/selectButton/SelectButton.js
src/selectButton/SelectButton.stories.js
src/selectButton/SelectButton.styles.js
src/stories/Releases.stories.mdx

Adjust Checkbox / Radio and Groups to accommodate small medium and large sizes with errors properly

---

package-lock.json
package.json
src/checkbox/Checkbox.js
src/radio/Radio.js
src/stories/Releases.stories.mdx

@NoahThomlison this should fix those console errors we are seeing on the modifier modal.

Updates proptypes to fix console error

---

Dockerfile
build/production/buildspec.yml

Upgrade to Node18

---

package-lock.json
package.json
src/card/Card.js
src/card/Card.stories.js
src/card/Card.styles.js
src/card/theme.js
src/stories/Releases.stories.mdx

@JakeHildy 
Here is new variant prop to add white color.  I am still trying to figure out the npm link issue but getting some error in admin site. 
https://github.com/Commerce7/admin-ui/assets/20227401/0e917b37-3918-417e-ac86-baafb6735f8b

Sc 8208 update card component to use variant prop for color

---

package.json

Test npm adminui deploy

---

package-lock.json
package.json
src/legend/Legend.js
src/legend/Legend.stories.js
src/legend/index.js
src/stories/Releases.stories.mdx

@JakeHildy Here is the new Legend component there is one Basic and also Grouped one.

Sc 8310 create custom legend component

---

package-lock.json
package.json
src/pieChart/PieChart.js
src/stories/Releases.stories.mdx

@JakeHildy 
We need to use currencyFormat helper to render currency which returns string. I just updated props to support string or number

support string prop type

---

package-lock.json
package.json
src/pieChart/PieChart.js
src/stories/Releases.stories.mdx

@JakeHildy I just fixed default props issue that we have in storybook, it was giving warning  since it expects element but I passed empty string in defaultProps

update label  default props in piechart

---

package-lock.json
package.json
src/index.js
src/progressBar/ProgressBar.js
src/progressBar/ProgressBar.stories.js
src/progressBar/ProgressBar.styles.js
src/progressBar/index.js
src/progressBar/theme.js
src/stories/Releases.stories.mdx

@JakeHildy @andreadyck I just created a custom generic progressbar component in admin-ui. So that we can consume in reporting dashboard. 
Also, minor package updates
https://github.com/Commerce7/admin-ui/assets/20227401/2c3dc7d6-4dd2-4cc3-89d4-3783fb4238e1

Sc 8545 create generic progressbar

---

package-lock.json
package.json
src/stories/Releases.stories.mdx

@yalcinos blocked by: https://github.com/Commerce7/admin-ui/pull/231

Major package updates

---

package-lock.json
package.json
src/input/ColorInput.js
src/input/Input.js
src/stories/Releases.stories.mdx

This passes the error messages through

Fix Color Picker Error Messages

---

.storybook/preview-head.html
README.md
package-lock.json
package.json
src/alert/Alert.styles.js
src/avatar/Avatar.styles.js
src/avatar/theme.js
src/common/form/styles.js
src/heading/Heading.styles.js
src/input/ColorInput.js
src/stories/Introduction.stories.mdx
src/stories/Releases.stories.mdx
src/table/Td.styles.js
src/table/Tfoot.styles.js
src/table/Th.styles.js
src/table/theme.js
src/tag/Tag.styles.js
src/ui/theme.js

- Headings: Increases font weight
- Tables: Reduce padding between columns, update footer background and add border
- Tags: Slightly reduce height
- Avatar: Slightly adjusts sizes for small + default, updates weight to bold
- Colour picker: Adds cursor: pointer to swatch
- Radio + checkboxes: Decreases description margin-top

Update misc styles and padding

---

package-lock.json
src/common/contextMenu/ContextMenuItem.styles.js
src/common/contextMenu/theme.js
src/common/dropdown/DropdownMenu.styles.js
src/common/form/styles.js
src/heading/theme.js
src/infoCard/InfoCard.styles.js
src/input/theme.js
src/legend/Legend.js
src/select/Select.styles.js
src/stories/Releases.stories.mdx
src/table/Td.styles.js
src/table/Th.styles.js
src/ui/theme.js

Misc updates. 
- Updates dropdown disabled text color
- Update dropdown icon spacing + min-width
- Updates input label + description spacing, updates select icon color
- Slightly increases heading size, base font size, and adds new font-size for tables (to keep it as it is now)

Misc updates to font sizes, field spacing, field colors

---

package-lock.json
package.json
src/heading/Heading.styles.js
src/heading/theme.js
src/stories/Releases.stories.mdx
src/table/Td.styles.js
src/tag/Tag.styles.js
src/ui/theme.js

Previewing the recent updates in admin, some sizes felt inconsistent. This updates them.

Update base and heading font size

---

package-lock.json
package.json
src/alert/Alert.styles.js
src/button/Button.styles.js
src/card/Card.styles.js
src/card/theme.js
src/cardLink/CardLink.styles.js
src/checkbox/Checkbox.styles.js
src/common/dropdown/DropdownMenu.styles.js
src/displayIcon/DisplayIcon.js
src/displayIcon/DisplayIcon.stories.js
src/displayIcon/DisplayIcon.styles.js
src/displayIcon/IconWrapper.js
src/icon/theme.js
src/infoCard/InfoCard.js
src/infoCard/InfoCard.styles.js
src/infoCard/theme.js
src/modal/Modal.styles.js
src/modal/ModalFooter.styles.js
src/modal/theme.js
src/noRecords/NoRecords.js
src/noRecords/NoRecords.styles.js
src/progressBar/ProgressBar.js
src/progressBar/ProgressBar.styles.js
src/selectButton/SelectButton.styles.js
src/stories/Releases.stories.mdx
src/ui/theme.js

This is low priority :) 
- `InfoCard`: Updates to a horizontal style
- `DisplayIcon`: Adds new background color to match status icon colour. Adds variant for warning
- Adds another border radius value to theme. Updates all border-radius to use variable from theme. (some are currently 3px vs 4px)
- `Modal`: Fixes cut off border-radius from footer
- `ProgressBar`: Adds Text component so that text line-height is consistent

Update InfoCard, DisplayIcon and border radius

---

package-lock.json
package.json
src/stories/Releases.stories.mdx
src/vividIcon/theme.js

@andreadyck 
Light theme; 
Dark theme;

fix green color issue on light theme

---

package-lock.json
package.json
src/stories/Releases.mdx

blocked by https://github.com/Commerce7/admin-ui/pull/277
CSS Loader major package update
We previsouly updated this on other packages so not too worried about it. 
https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md

2024 05 13 major package updates

---

package-lock.json
package.json
src/stories/Releases.mdx

blocked by https://admin-ui-docs.commerce7.com/
style-loader major package update
Same as the CSS loader, did it previsouyl so not too worried
https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md

2024 05 13 major package updates 2

---

package-lock.json
package.json
src/linkButton/LinkButton.js
src/stories/Releases.mdx

@NoahThomlison Adding onClick prop to Linkbutton

add onclick prop to linkbutton

---

package-lock.json
package.json
src/stories/Releases.mdx
src/ui/theme.js
src/vividIcon/theme.js

@andreadyck 
light mode;
dark mode;

update c7Color palette and vividicon colors

---

package-lock.json
package.json
src/stories/Releases.mdx

https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md

major package update

---

package-lock.json
package.json
src/icon/theme.js
src/infoCard/InfoCard.js
src/infoCard/InfoCard.stories.js
src/infoCard/InfoCard.styles.js
src/stories/Releases.mdx

- Update `InfoCard` to add the iconVariantOverride prop
- Update `InfoCard` to conditionally render title and subtitle
- Adds colors for info and white variants for icon colors and icon background colors

Sc 15369 update info card

---

package-lock.json
package.json
src/noRecords/NoRecords.js
src/noRecords/NoRecords.stories.js
src/stories/Releases.mdx

add new iconVariant prop for noRecords

---

package-lock.json
package.json
src/stories/Releases.mdx

does not seem to be any issue updating this package
release notes:
https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md

major package update - webpack-cli

---

.storybook/preview.js
package-lock.json
package.json
src/alert/Alert.stories.tsx
src/avatar/Avatar.stories.tsx
src/breadcrumbs/Breadcrumbs.stories.tsx
src/checkbox/Checkbox.stories.tsx
src/checkboxGroup/CheckboxGroup.stories.tsx
src/columns/Columns.stories.tsx
src/datePicker/DatePicker.stories.tsx
src/displayIcon/DisplayIcon.stories.tsx
src/icon/Icon.stories.tsx
src/infoCard/InfoCard.stories.tsx
src/input/Input.stories.tsx
src/legend/Legend.stories.tsx
src/lineBreak/LineBreak.stories.tsx
src/modal/Modal.stories.tsx
src/nav/Nav.stories.tsx
src/pieChart/PieChart.stories.tsx
src/progressBar/ProgressBar.stories.tsx
src/radio/Radio.stories.tsx
src/radioGroup/RadioGroup.stories.tsx
src/select/Select.stories.tsx
src/stepper/Stepper.stories.tsx
src/stories/Releases.mdx
src/subMenu/SubMenu.stories.tsx
src/tabs/Tabs.stories.tsx
src/text/Text.stories.tsx
src/textarea/Textarea.stories.tsx
src/vividIcon/VividIcon.stories.tsx

This pull request refactors story files across multiple components to improve maintainability and documentation fixing the code samples.
* Converted example components (e.g., `BasicExample`, `DisabledExample`) into `Story` objects with `render` functions. 
* Removed redundant exports for previously defined stories.
* Refactored `BasicExample` and `ErrorExample` into `Story` objects with `render` functions. 
* Removed redundant exports for previously defined stories.
* Converted example components (e.g., `BasicExample`, `DisabledExample`) into `Story` objects with `render` functions and added `parameters` for documentation. 
* Refactored `BasicExample`, `VariantsExample`, `SizesExample`, `OnClickExample`, and `IconListExample` into `Story` objects with `render` functions and added …

SC-16063 | FIX - Adjust code sample docs

---

package-lock.json
package.json
src/stories/Releases.mdx

https://github.com/cypress-io/eslint-plugin-cypress/releases
removes flat config but thats about it

major-package-update-eslint-plugin-cypress

---

package-lock.json
package.json
src/stories/Releases.mdx

Reverts Commerce7/admin-ui#356

Revert "minor package updates"

---

Dockerfile

add CloudFront invalidation after deploy

add CloudFront invalidation after Storybook deploy
