Commerce7/admin-ui

- Dockerfile
- package.json
- src/alert/Alert.js
- src/alert/Alert.styles.js
- src/stories/Releases.stories.mdx
@tlouth19 I was passing size into the StyledIcon which was throwing this error since the Icon component itself had a size prop that wasn't matching the small Alert prop types.
> Fix Alert Icon Size Prop error

- package.json
- src/datePicker/DatePicker.js
- src/stories/Releases.stories.mdx
@JakeHildy this updates the `DatePicker` component to show a calendar icon always
Blocked by #6 (waiting on the NPM publish fix before merging that PR)
> Added calendar icon to datepicker

- package.json
- src/avatar/Avatar.js
- src/avatar/Avatar.styles.js
- src/avatar/theme.js
- src/stories/Releases.stories.mdx
@andrewkamphuis the avatar will now show a user icon instead of just am empty circle if there is no initials or profile image
> Added icon to avatar when no image or label is provided

- package.json
- src/displayIcon/DisplayIcon.js
- src/displayIcon/DisplayIcon.stories.js
- src/displayIcon/DisplayIcon.styles.js
- src/displayIcon/IconWrapper.js
- src/displayIcon/index.js
- src/icon/Icon.stories.js
- src/index.js
- src/stories/Releases.stories.mdx
@tlouth19 this adds the DisplayIcon to admin UI like we discussed. I extended some of the styling and theme from Icon but defined new styles that are related to the size so we can remove that from Icon in the future.
> Add DisplayIcon to AdminUI

- package.json
- src/button/theme.js
- src/stories/Releases.stories.mdx
- src/ui/theme.js
@JakeHildy the links in dark mode are hard to read right now inside admin. This adds a `linkColor` to the theme object, so we can use it in admin. 
Also updated the LinkButton to use this new colour in dark mode.
> Added link color to c7 theme object

- package.json
- src/breadcrumbs/Breadcrumb.js
- src/stories/Releases.stories.mdx
@tlouth19 this removes the extra `type` on breadcrumbs that end up as anchor tags
> Remove type on breadcrumbs

- package.json
- src/buttonMenu/ButtonMenu.js
- src/stories/Releases.stories.mdx
@tlouth19 this fixes the warning that kept showing up on pages with the ButtonMenu component. Old default icon size prop that was missed.
blocked by: https://github.com/Commerce7/admin-ui/pull/41
> Sc 1610 button menu bug fix

- package.json
- src/cardLink/CardLink.styles.js
- src/stories/Releases.stories.mdx
@JakeHildy I was making some changes in admin settings, and noticed the icons were collapsing without a min width/height on them if the labels are long
> Fixed css issue in CardLink component

- package.json
- src/common/form/styles.js
- src/stories/Releases.stories.mdx
@JakeHildy this fixes a small issue with the checkboxes/radios: https://app.shortcut.com/commerce7/story/1405/update-checkbox-to-inline-flex-to-avoid-accidental-checking-off
> Updated checkbox and radio to use inline display

- package.json
- src/index.js
- src/stories/Releases.stories.mdx
- src/ui/theme.js
@JakeHildy there are lots of spots in admin where we need a red for errors, and instead of always guessing on which red to use I added an errorColor to the theme here (currently they are the same for dark and light mode). 
Also added the color object as an export in admin-ui. We have lots of theme files in admin that need the hex colors updated, but they can't access the styled components theme because they're in a theme.js file or similar. I didn't add this to the release notes, because it would be nice to remove this once all of the admin components are brought over to admin-ui.
> Added error color to global theme

- package-lock.json
- package.json
- src/stepper/Step.js
- src/stories/Releases.stories.mdx
@tlouth19 the step component was throwing a warning cause it was expecting a string for the step prop but we were giving it a number everywhere.
> Fixed Step propType warning

- package-lock.json
- package.json
- src/alert/Alert.styles.js
- src/stories/Releases.stories.mdx
@tlouth19 this updates the alert to have a border colour equal to the background colour so that the alerts on alternate background look better.
> Updated Alert border colour to background colour

- package-lock.json
- package.json
- src/infoCard/InfoCard.js
- src/infoCard/InfoCard.styles.js
- src/stories/Releases.stories.mdx
@tlouth19 this updates the infoCard component to accept node type on the title, subtitle and label props. Also tweaked the grid wrapper minmax to 225px so it will match closer to the existing widths.
> Updated infoCard prop types and Grid minmax

- package.json
- src/common/dropdown/DropdownMenu.js
- src/common/dropdown/DropdownMenu.styles.js
- src/stories/Releases.stories.mdx
- src/utils/hooks/useWindowSize.js
@JakeHildy this fixes both the ContextMenu and ButtonMenu, and should not kill the viewport on small screens anymore.
> Fixed dropdown overflow on smaller viewports

- package.json
- src/selectButton/SelectButton.styles.js
- src/stories/Releases.stories.mdx
https://app.shortcut.com/commerce7/story/2789/if-loyalty-points-can-no-longer-be-redeemed-on-order-hide-blue-alert
> Fixed select button disabled font color

- package-lock.json
- package.json
- src/alert/Alert.stories.js
- src/stories/Releases.stories.mdx
@NoahThomlison we forgot to bump package so deployment failed when trying to publish to npm. This new PR bumps the package and `npm i` to update package-lock. Also updates stories so it makes a bit more sense
> Bump AdminUI package and release notes

- package-lock.json
- package.json
- src/heading/Heading.js
- src/heading/Heading.stories.js
- src/heading/Heading.styles.js
- src/heading/theme.js
- src/stories/Releases.stories.mdx
@andreadyck this adds h4 headings to Admin-ui. We override level 3's all the time to have 18px font-size so this is one "incremental step" towards being able to remove some of the custom styles in admin.
> Add level 4 Heading

- package-lock.json
- package.json
- src/button/Button.js
- src/button/Button.stories.js
- src/button/Button.styles.js
- src/stories/Releases.stories.mdx
Currently buttons require children. This is an issue when we want a button without text but with an icon.
Remove children from required and give it a default value of null
Update styling to remove the margins from the icon when there is no children present
Add example of new button styling to story for Icon button
> updates to remove children from the required on buttons

- package-lock.json
- package.json
- src/buttonMenu/ButtonMenu.js
- src/stories/Releases.stories.mdx
Button menu needs to be updated with new hasChildren prop so that the styling is correct
Since on a buttonMenu the children are required I simply pass true in instead of the logic on the other buttons
with
without
> Button menu styling fix

- package-lock.json
- package.json
- src/contextMenu/ContextMenu.stories.js
- src/contextMenu/ContextMenuMoreActions.js
- src/stories/Releases.stories.mdx
@NoahThomlison this allows us to pass in a "label" prop to the ContextMenuMoreActions so we can override the default "More Actions" label if we want.
> More Actions override

- package-lock.json
- package.json
- src/breadcrumbs/Breadcrumb.styles.js
- src/heading/theme.js
- src/nav/theme.js
- src/stories/Releases.stories.mdx
- src/text/theme.js
- src/ui/theme.js
- Added hover state to breadcrumb links and changed spacing slightly
- Decreased h3 + h4 margin-bottom slightly
- Added new colours `purple100`, `purple200`, `purple300`
- Tweaked colours for `orange200`, `blue100`,  `blue200`, `blue600`, `slate200`, `slate300`
Old
New
Old
New
> Misc updates

- package-lock.json
- package.json
- src/legend/Legend.js
- src/legend/Legend.stories.js
- src/pieChart/PieChart.js
- src/pieChart/PieChart.stories.js
- src/stories/Releases.stories.mdx
@JakeHildy @andreadyck 
I added isVertical prob to Legend so that when ever it is true the Legend is going to render vertically. Otherwise it will render inline.
I also created a story in the PieChart storybook doc that is  **With Custom Legend** so that Pablo can use this example to create PieChart with Inline Legend instead of using the one in the Recharts.
FYI: Once this one is merged. I am going to update admin to use isVertical in the reporting.
PieChart stories;
Legend Stories;
> Sc 8538 update pie chart component to render custom inline legend

- package-lock.json
- package.json
- src/button/Button.js
- src/stories/Releases.stories.mdx
@JakeHildy This will help us enable/disable form validation that comes from HTML. So that the required pop up that comes from HTML will be gone if you make this true.
> add novalidation prop to button

- .storybook/manager.js
- .storybook/preview-head.html
- README.md
- package.json
- src/stories/Introduction.stories.mdx
- src/stories/Releases.stories.mdx
- src/ui/theme.js
In admin ui I cannot figure out how to change the default font of storybook for the following areas below. Andrea has stated she does not care about these items
> Sc 9083 change admin UI font

- package.json
- src/stories/Releases.stories.mdx
- src/table/Td.styles.js
- src/table/Tfoot.styles.js
- src/tag/Tag.js
- src/tag/Tag.styles.js
- Tables: There was an issue with the new padding when there is only a single column in the table
- Tags: "g" was getting cut off vertically
- Tags: Updates "x" text to symbol and colour to match tag text
> Update table padding and tag close button

- package-lock.json
- package.json
- src/stories/Releases.stories.mdx
- src/table/Td.styles.js
- Right now, we have padding added to linked tables in Admin (which overrides what is set in Admin UI)
- Most of our tables have linked rows so those all display fine, but if a partner is using the table component on its own which doesn't have the linking, the table isn't aligned with the header properly when only one column exists.
I will need to make another change to Admin after this PR is through.
- Fix table padding for single column tables
> Fix table padding for single column tables

- package-lock.json
- package.json
- src/displayIcon/DisplayIcon.js
- src/displayIcon/index.js
- src/index.js
- src/stories/Releases.stories.mdx
@NoahThomlison 
I revert the icon name from Display to DisplayIcon. This was causing Admin repo crashing because we are using DisplayIcon name in admin so I just revert back to DisplayIcon. Once this PR is merged I will update packages in admin repo
> bring back DisplayIcon export name

- package-lock.json
- package.json
- src/heading/Heading.js
- src/heading/Heading.stories.js
- src/heading/Heading.styles.js
- src/stories/Releases.stories.mdx
@JakeHildy 
Andrea would like to add margin prop to Heading. Because currently we are usually override Heading marginBottom always to make it 5px. So this pr will add new prop to Heading component so that we can override marginBottom.
I have one ticket in admin to cleanup all custom style for margin-bottom to replace with this prop
> add marginBottom prop to override heading component margin

- package-lock.json
- package.json
- src/linkButton/LinkButton.js
- src/linkButton/LinkButton.stories.js
- src/stories/Releases.mdx
@NoahThomlison @andreadyck 
We would like to show loading status for Apple pay project for Link Button. This `loading` prop will show loading spinner for link button.
> add loading prop to show loading spinner for link button

- package-lock.json
- package.json
- src/stories/Releases.mdx
- src/ui/theme.js
@andreadyck This pr is going to update the color plate.
One think I didn't update is that `invertedBackgroundColor`. Because that variable is inside of CardLink component in admin-ui.  (Once this PR is merge I will open Admin PR To update the version)
If you want me to update to slate400, the visual changes will be like this. I liked the other way around but let me know if you wanna do that changes.
Before updating  `invertedBackgroundColor` ;
After updating `invertedBackgroundColor` color to slate400;
> update color codes and add new ones

- package-lock.json
- package.json
- src/nav/Nav.js
- src/nav/Nav.stories.js
- src/nav/Nav.styles.js
- src/nav/theme.js
- src/stories/Releases.mdx
@andreadyck @NoahThomlison 
Currently our admin repo creating by sideBar by using custom CSS instead of consuming from admin-ui Nav component.
We need isOpen props in admin-ui so that we can consume to close/open for mobile version as well.
This does not effect current component because the default props is true
> add isOpen props for navbar 

- package-lock.json
- package.json
- src/modal/ModalContent.js
- src/stories/Releases.mdx
@NoahThomlison @jasonandres @joshclysdale 
This can go on later. This is just refactoring that I realized we can pass disabled props to react focus lock library to disable. No need for additional if conditions.
Better to test after admin pr is merged;
https://github.com/Commerce7/admin/pull/7471
> refactor modalContent to accept disable props for React lock

- package-lock.json
- package.json
- src/infoCard/InfoCard.styles.js
- src/infoCard/theme.js
- src/stories/Releases.mdx
@andreadyck This is the work we need to use the theme styles for InfoCard. once this merges, will update admin to use latest package
For secondary color; I created `secondaryFontColor` because we have different theme file for Info card and works based of variants.
The sketch design has lower-case for title but we currently use upper case in admin, let me know I can remove `text-transform` in admin-ui if you want.
After admin uses new version ;
> update card component styles to match with design system

- package-lock.json
- package.json
- src/stories/Releases.mdx
- src/switch/Switch.styles.js
When the Switch component has a label with a long length, the round/white part of the switch is not aligned. The white part of the switch should always display on top of the blue toggle background
Add minimum width to the switch
> Risk Level: Low
Describe how to test it
> SC-14794 | Adjust Switch min width

- package-lock.json
- package.json
- src/stories/Releases.mdx
- src/tabs/Tabs.styles.js
Tabs wrap on some desktop sizes so we want to reduce horizontal padding so that more can fit in a single line
Update Tabs component padding from 15px to 10px
> Risk Level: Low
Describe how to test it
> SC-15177 | Update Tabs component padding

- package-lock.json
- package.json
- src/selectButton/SelectButton.stories.js
- src/selectButton/SelectButton.styles.js
- src/selectButton/theme.js
- src/stories/Releases.mdx
**This one isn't a priority to get in.**
- Select buttons weren't using all of the set colours (some referenced the general theme instead)
- Border colours for default and disabled buttons didn't match other field and button styles
- Update select buttons to use the theme colours
- Update colours for borders to match other fields and buttons
- Update the stories example page to have 1 example per button type: Default, Selected, Loading, Disabled
> Update select button styles

- package-lock.json
- package.json
- src/stories/Releases.mdx
- src/tag/Tag.styles.js
When the search component is used in a modal, items with longer titles are cut off which decreases the usability.
This was reported by a client for Reporting > Queries specifically, but could be an issue anywhere the field is used in a modal.
Wrap tag text
> Risk Level: Low 
Describe how to test it
> SC-15228 | Update tag component to wrap text

- package-lock.json
- package.json
- src/stories/Releases.mdx
This pull request updates the `@commerce7/admin-ui` package to version `2.0.7` and includes changes to dependencies and documentation. The most notable updates are the upgrade of React and React DOM to version `19.1.0`, the removal of the `prop-types` package, and the addition of release notes for version `2.0.7`.
* Upgraded `react` and `react-dom` dependencies from version `18.3.1` to `19.1.0`.
* Removed `prop-types` package, which is no longer supported or used.
* Updated the package version in `package.json` from `2.0.6` to `2.0.7`.
* Added release notes for version `2.0.7` in `src/stories/Releases.mdx`, detailing the React and React DOM upgrade and the removal of the `prop-types` package.
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#breaking-changes
> SC-16037 | FEAT -  Update React to 19
